format = """
$git_branch\
$git_status\
$line_break\
$character\
$directory\
"""

# Global timeout setting for all commands
command_timeout = 1000


[directory]
truncation_length = 10
truncate_to_repo = false
style = "#A4E4E0" # Highlight (2.7%)


[character]
success_symbol = "▲"
error_symbol = "▲"
vimcmd_symbol = "▲"
vimcmd_replace_one_symbol ="▲"
vimcmd_replace_symbol= "▲"
vimcmd_visual_symbol ="▲"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M"
style = "#586269" # Mid Gray


[git_branch]
format = "  [$symbol$branch]($style) "
style = "#5ABDBC" # Teal Bright (1.7%)
symbol = "\ue0a0"


[git_status]
style = "#CEF5F2" # Foreground

[shell]
disabled = true

