format = """
$git_branch\
$git_status\
$line_break\
$character\
$directory\
"""

# Global timeout setting for all commands
command_timeout = 1000


[directory]
truncation_length = 10
truncate_to_repo = false
style = "#CDD8D7" # ライトグレー: ディレクトリ


[character]
success_symbol = "▲"
error_symbol = "▲"
vimcmd_symbol = "▲"
vimcmd_replace_one_symbol ="▲"
vimcmd_replace_symbol= "▲"
vimcmd_visual_symbol ="▲"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M"
style = "#7E8A89" # モノクロ基調 - 中間グレー


[git_branch]
format = "  [$symbol$branch]($style) "
style = "#AAB6B5" # 明るいグレー: Gitブランチ
symbol = "\ue0a0"


[git_status]
style = "#D7E2E1" # モノクロ基調 - 前景

[shell]
disabled = true

