format = """
$git_branch\
$git_status\
$line_break\
$character\
$directory\
"""

# Global timeout setting for all commands
command_timeout = 1000


[directory]
truncation_length = 10
truncate_to_repo = false
style = "#9DDCD9" # Heading Cyan


[character]
success_symbol = "▲"
error_symbol = "▲"
vimcmd_symbol = "▲"
vimcmd_replace_one_symbol ="▲"
vimcmd_replace_symbol= "▲"
vimcmd_visual_symbol ="▲"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M"
style = "#525B65" # Slate Mid


[git_branch]
format = "  [$symbol$branch]($style) "
style = "#6CD8D3" # Vibrant Teal
symbol = "\ue0a0"


[git_status]
style = "#CEF5F2" # Main Foreground

[shell]
disabled = true

